### ISSUE TITLE
schema: using LCS to derive field names for SaintCoinach groups results in awkward names

### ISSUE THREAD

**Issue by aurieh** [ackwell/ironworks#27]
For example, excerpt from`Recipe`:
```rs
StructField {
    offset: 5,
    name: "m{Ingredient}",
    node: Array {
        count: 10,
        node: Struct(
            [
                StructField {
                    offset: 0,
                    name: "Item{Ingredient}",
                    ...
                },
                StructField {
                    offset: 1,
                    name: "Amount{Ingredient}",
                    ...
                },
            ],
        ),
    },
},
```

It might be a good idea to switch to using longest common substring instead? I translated [the example algorithm from Wikipedia](https://en.wikipedia.org/wiki/Longest_common_substring#Dynamic_programming) for reference: [gist](https://gist.github.com/aurieh/ec609f4087a3d3cf89b3b2d14fd196cb). It passes all of the existing tests minus `distributed()`, as it should.

**Comment by ackwell** [comment]
I tested both at the outset and was generally unimpressed with both. LCS stuck because it matched other tools I'd written at the time. While it's far from perfect, it's inherently limited by StC not naming its structures.

I'd recommend using `exdschema` rather than `saint_coinach`. I may update StC's code path to generate something less silly, but it's not a priority.

**Comment by aurieh** [comment]
> I tested both at the outset and was generally unimpressed with both. LCS stuck because it matched other tools I'd written at the time. While it's far from perfect, it's inherently limited by StC not naming its structures.

Fair enough. In hindsight, neither solution is inherently better than the other.

> I'd recommend using `exdschema` rather than `saint_coinach`.

I guess it's out of scope for this issue, but yes, that is what I tried initially. Unfortunately though, it seems that exdschema is even less usable as it is more often wrong than it is right, e.g. [exdschema Item](https://github.com/xivdev/EXDSchema/blob/26848005807d691e5466f3cda7ac838d264e9854/Schemas/2024.03.27.0000.0000/Item.yml#L4-L9) vs [StC Item](https://github.com/xivapi/SaintCoinach/blob/1d43d4427797a86fe68a8815fca3e1c88a51ec04/SaintCoinach/Definitions/Item.json#L5-L27), the entire [Recipe](https://github.com/xivdev/EXDSchema/blob/26848005807d691e5466f3cda7ac838d264e9854/Schemas/2024.03.27.0000.0000/Recipe.yml) schema is [completely wrong](https://github.com/xivapi/SaintCoinach/blob/1d43d4427797a86fe68a8815fca3e1c88a51ec04/SaintCoinach/Definitions/Recipe.json) and so on.

**Comment by ackwell** [comment]
I can't verify right now, on phone - but did you check the order of columns? stc uses column array order, exdschema uses byte offset order. if you try to read exdschema with unsorted columns it's gonna be wrong.

see https://github.com/ackwell/boilmaster/blob/main/src/read/read.rs#L66 for an example of handling this

if there is still inaccuracies after doing so, please do raise them or pr fixes to exdschema - it's a community project and benefits from corrections

**Comment by aurieh** [comment]
> I can't verify right now, on phone - but did you check the order of columns? stc uses column array order, exdschema uses byte offset order. if you try to read exdschema with unsorted columns it's gonna be wrong.

Thanks, I was unfamiliar with this. I'll make the necessary adjustments to my code and see what works. I should probably file an issue and possibly a PR to document this on the exdschema repo, as I did go over both the README and Usage.md prior to writing my previous comment and didn't find anything about the column order. Perhaps I missed it though, in which case, my bad!

> if there is still inaccuracies after doing so, please do raise them or pr fixes to exdschema - it's a community project and benefits from corrections

Of course, will do!
